[package]
name = "fsk-traffic-control"
version = "2.0.0"
license = "Beerware"
description = "Formula Student Korea Traffic Controller"
authors = ["luftaquila <mail@luftaquila.io>"]
repository = "https://github.com/luftaquila/fsk-traffic-control"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = ["shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
open = "5.3.0"
chrono = "0.4.38"
serialport = "4.5.0"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
